### ISSUE TITLE
Проблема с url стартовой страницы

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#109]
Использую версию 7.12.8. Не получается поменять url стартовой старницы. Делал по официальной документации, пробовал искользовать аттрибут route="/home", но url не меняется, получаю ошибку "Metadata by url '/home' not found!". Так же пробовал через application.xml, но получаю ошибку "Source type [application] hadn't been registered". Добавлял в проект зависимость n2o-config, но это никак не повлияло на ошибку. Касательно ошибок в гугле ничего полезного найти не смог. Есть ли какие-то еще способы поменять url страницы или как то исправить ошибку с application?

**Comment by iryabov** [comment]
В N2O нет редиректа с "/" на "/home", это следует делать самостоятельно с помощью фильтров сервера.
В N2O есть настройка страницы, которая откроется по "/". Для этого можно использовать атрибут  `welcome-page-id` https://n2o.i-novus.ru/docs/guides/xml/application/#Application. Правда, он появился в более поздних версиях.
Или использовать настройку n2o.homepage.id=index, где index id страницы.
Чтобы на "/home" открылась страница, нужно в header > nav > page задать атрибут `route="/home"`.
Вообще советую использовать более свежую версию N2O, например, 7.20.

**Comment by ilinykh-ie** [comment]
Понятно, спасибо! А можете еще подсказить, можно ли как то извабиться от символа # в url? То есть сделать например localhost:8080/home а не localhost:8080/#/home?

**Comment by iryabov** [comment]
Нет, от хеша никак не избавиться.

**Comment by ilinykh-ie** [comment]
Еще раз спасибо
