### ISSUE TITLE
Скачивание файла через rest эндпоинт

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#115]
Добрый день, я пытаюсь реализовать выгрузку файла по кнопке. При нажатии отправляется get запрос, эндпроин возвращает ResponseEntity<Resource> с хэдером attachment. Если этот же запрос сделать через браузер, то начинается загрузка файла, Но когда я делаю это через кнопку n2o, то получаю JsonParseException. То есть он пытается распарсить ответ, вместо того чтобы начать загрузку. Подскажите пожалуйста, в каком формате нужно возвращать ответ от эндпоинта или какие атрибуты добавить в тег <invocation>, чтобы при нажатии кнопки начиналась загрузка файла.

**Comment by iryabov** [comment]
Вот пример, где кнопка открывает ссылку https://n2oapp.net/sandbox/editor/bzMVh/
В данном случае сайт, но можно задать ссылку на скачивание файла и оно начнется.
Основное - это действие <a> , и target=newWindow

**Comment by ilinykh-ie** [comment]
Понятно, спасибо. Хотелось конечно сделать без редиректа. Issue тогда закрываю.
