### ISSUE TITLE
Получение списка элементов для выпадающего списка в фильтрах.

### ISSUE THREAD

**Issue by EvillCat** [i-novus-llc/n2o-framework#117]
Здравствуйте
Подскажите, пожалуйста, есть ли возможность предзаполнения элементов  <ctrl:option> в <ctrl:select> с сервера (из java кода или рестовым запросом). Я хочу, чтобы это было не фиксированное множество вариантов выбора, а чтобы они получались в результате работы метода.

**Comment by Rgalina** [comment]
Доброго дня. У ctrl:select есть атрибут query-id, в котором можно указать выборку для получения данных. При этом options указывать не надо. Подробнее можно посмотреть тут https://n2o.i-novus.ru/docs/guides/xml/field#select

**Comment by EvillCat** [comment]
Спасибо
