### ISSUE TITLE
Получаения номера страницы.

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#120]
Добрый день. У меня есть таблица, на которой реализована пагинация. Могу ли я как-то получить номер страницы, которую сейчас просматриваю? Мне нужно использовать эти данные  для перехода по ссылке при нажатии кнопки (через query-param). Пробовал указывать ref-model="datasource", но не смог найти примеры для него, чтобы посмотреть синтаксис и возможность реализации.

**Comment by AlekseySokolov** [comment]
Добрый день, насколько знаю не получиться через xml. 
Можно реализовать через кастом кнопку на фронте (забрать page из redux-store -> datasource[id].page и отдать куда нужно)

**Comment by iryabov** [comment]
Текущая страница не хранится в моделях данных, поэтому отправить ее в ссылке через xml не получится.

**Comment by ilinykh-ie** [comment]
А подскажите тогда пожалуйста, есть ли какой то способ выгрузить данные по текущей странице таблицы? То есть те данные, которые отфильтровались и находятся на странице, которая сейчас открыта?

**Comment by Rgalina** [comment]
Посмотрите в network запросы /data

**Comment by ilinykh-ie** [comment]
> 

А можете подсказать где это посмотреть? В документации даэе через поисковик ничего такого не могу найти 
![image](https://user-images.githubusercontent.com/67537056/161713661-d19efb47-aff5-4ee0-9b20-04341036bfe5.png)

**Comment by ilinykh-ie** [comment]
Понятно, но пытался узнать, как это сделать средствами фреймворка. Как уже ответили выше, через xml я не смогу вытащить номер страницы на сколько я понял
