### ISSUE TITLE
Модалка для экспорта данных в csv и иные форматы

### ISSUE THREAD

**Issue by tagirmh** [i-novus-llc/n2o-framework#123]
![Screenshot_2](https://user-images.githubusercontent.com/103200740/162224762-da31d689-af7b-4cc7-9b89-161f0940dac8.png)

**Comment by iryabov** [comment]
https://n2oapp.net/sandbox/editor/YKrB3/

Можно передать фильтры снизу в модалку через query параметры
https://n2o.i-novus.ru/docs/guides/manual/routing#Routing_field
