### ISSUE TITLE
Выбор записи из таблицы

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#127]
Добрый день. У меня возникла проблема с выбором одной записи из таблицы и последующими действиями с этой записью по кнопке. Если я ставлю selection="checkbox" то при попытке выбрать запись выделяются все строки. Если ставлю selection="radio", то при загрузке визуально показываетс как будто сразу все выбраны и снять выделение нельзя.  Выглядит как будто полученная коллекция воспринимается  фреймворком как один объект. Аналогичная ситуация  с selection="active". При этом при нажатии по кнопке всегда передаются данные из 1й строки. Смотрел на сайте примеры, у меня отличается только тем, что данные получаются не из json файла, а через метод на java (возвращаемый тип CollectionPage)
![image](https://user-images.githubusercontent.com/67537056/165085883-f0444126-5efe-470f-b664-571f3a7a8a5d.png)
![image](https://user-images.githubusercontent.com/67537056/165086526-4865a5e5-7b96-4c8a-8ef5-138276ced199.png)

**Comment by iryabov** [comment]
Это из-за того, что у выборки таблицы не задано поле id, либо он одинаковый для  всех строк.

**Comment by ilinykh-ie** [comment]
То есть если у меня нет поля id, то я не смогу операции с конкретной строкой по другим полям производить?

**Comment by iryabov** [comment]
Не обязательно передавать id с бекенда, можно использовать обычный индекс, он задается вот так
```        
<field id="id"/>
```

**Comment by ilinykh-ie** [comment]
Понятно, спасибо!
