### ISSUE TITLE
Валидация по условию

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#132]
Добрый день. Я пытаюсь реализовать валидацию поля в зависимости от выбранного radio-group. Написал такой пример в sandbox. Проблема заключается в там, что вне зависимости от условя в enabled валидация отрабатыват всегда. Работаю на версии 7.20 и ищу решение именно на этой версии. Проверил ради интереса в sandbox на версии 7.22, там отрабатывает корректно. Подскажите, в чем может быть проблема и как реализовать этот механизм на версии 7.20.

https://7-20.n2oapp.net/sandbox/editor/HrEuM/

**Comment by iryabov** [comment]
Это баг.
Можно обойти вот так (если суть только в обязательности)
https://7-20.n2oapp.net/sandbox/editor/0Dfro/
этим способом нельзя настроить сообщение

**Comment by ilinykh-ie** [comment]
Спасибо! Закрываю
