### ISSUE TITLE
Получение данных из парметра в url

### ISSUE THREAD

**Issue by ilinykh-ie** [i-novus-llc/n2o-framework#135]
Добрый день, подскажите, можно ли на странице (page.xml) получить значение параметра из url? Например страница открывается по пути http://localhost:8080/#/app?test_param=test. Я хочу получить значение параметра test_param и передать его в модальное окно. Пробовал так (query-param name="param" value="${test_param}"), но значение не определяется. Есть ли для этого какой-то способ? В документации не смог найти

**Comment by iryabov** [comment]
Добрый день. Да, есть такая возможность.
Для этого придется сначала положить значение из url на форму в скрытое поле (или не скрытое, не принципиально).
А затем из поля прокинуть в модальное окно.
https://next.n2oapp.net/sandbox/view/hWxEP/#/?test_param=1
https://sandbox.n2oapp.net/editor/hWxEP/

**Comment by ilinykh-ie** [comment]
Спасибо!
