### ISSUE TITLE
Обмен данными между n2o и кастомными react компонентами

### ISSUE THREAD

**Issue by vladislavnikonov** [i-novus-llc/n2o-framework#150]
Добрый день, как передать id строки из таблицы n2o в кастомный реакт компонет страницы? 

Есть таблица \<table\> и при клике на кнопку "Подписать" открывается модальное окно с кастомной страницей.  Возможно ли передавать id строки?
![fss](https://user-images.githubusercontent.com/55946429/205002189-e85b6f81-7fd2-4dd0-a771-d387907607db.png)

**Comment by Rgalina** [comment]
Вот тут есть пример передачи параметра в url открываемой модалки https://sandbox.n2oapp.net/editor/CNg9q/?file=index.page.xml

**Comment by vladislavnikonov** [comment]
Вы меня не совсем поняли. Передача между компонентами n2o мне ясна. Вопрос в другом:
Как отсюда 
![image](https://user-images.githubusercontent.com/55946429/205057845-acbb9baf-c71d-4df3-88bf-f9407582d3b7.png)
передать сюда?
![image](https://user-images.githubusercontent.com/55946429/205057681-5639bcda-1d6d-4917-858f-a341f1c88500.png)

**Comment by AlekseySokolov** [comment]
На кастомный page придут, datasource и model (префикс модели).
С их помощь обратитесь к redux модели и заберите необходимые данные (прим. models.resolve.[id_modal_main])

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/28859492/205266151-beeaef7d-515f-49bf-9cf1-0ab3017f1f27.png">
