### ISSUE TITLE
Context-path в своем react проекте

### ISSUE THREAD

**Issue by vladislavnikonov** [i-novus-llc/n2o-framework#157]
Как менять context-path в своем react проекте?

Добавил настройку в application.properties, но могу изменять только порт.
![image](https://user-images.githubusercontent.com/55946429/207002792-a54a7ad3-3d88-43e9-aff8-394f6f74361c.png)

Ссылки на ресурсы, типа
/static/js/181.309317d1.chunk.js
формируются без учета контекста.

**Comment by PredokMiF** [comment]
Если фронт собирается при помощи `create-react-app` при помощи `react-scripts` (что скорее всего так), то рядом с файлом `package.json` можно создать файл `.env` со строкой `PUBLIC_URL="/mycontext"`. В prod-сборке у статики будут пути с контекстом, но в dev-версии эта настройка не активна.

**Comment by PredokMiF** [comment]
Так не получится. Проблема в том, что задание контекста для бэкенда и для фронтенда происходит в разное время. Бэкэнд запускается в момент старта jar'ника и на него можно повлиять настройками в момент запуска, а фронтенд не запускается, он просто отдается в виде статики по требованию без процессинга. Т.е. вся статика для фронтенда билдится заранее, упаковывается в jar и лежит там неизменяемая.
Попробуйте в `.env` файле задать PUBLIC_URL="./", это заставит статику грузиться относительно пути по которому открылся index.html. Должно помочь.
