### ISSUE TITLE
Закрытие кастомного модального окна

### ISSUE THREAD

**Issue by vladislavnikonov** [i-novus-llc/n2o-framework#158]
Добрый день, как добавить на кастомную кнопку "Отправить" закрытие модального окна?

![image](https://user-images.githubusercontent.com/55946429/208606619-e9e9cf92-85f9-47f6-8f7f-aabbdf00e90e.png)
![image](https://user-images.githubusercontent.com/55946429/208606917-d9883cbc-6089-477b-9cb6-b24ccb9dae65.png)

**Comment by Rgalina** [comment]
пример вот тут можно посмотреть https://sandbox.n2oapp.net/editor/DI565/?file=modal.page.xml

**Comment by vladislavnikonov** [comment]
Добрый день, вы опять меня не правильно поняли. Через модальное окно я открываю кастомную страницу.
![image](https://user-images.githubusercontent.com/55946429/208851352-4e7e2597-7184-4056-859d-589d48108058.png)
![image](https://user-images.githubusercontent.com/55946429/208851510-b7461f92-e07b-4820-85ac-bfeb2648fbda.png)
![image](https://user-images.githubusercontent.com/55946429/208851673-86bcb37e-daf7-4a89-9b17-bcc46ab44e0c.png)

Тут у меня есть компонент "CreateErsSignature", который отправляет данные на сервер.
![image](https://user-images.githubusercontent.com/55946429/208851966-9318e357-ccaf-4355-90eb-4394db18e09e.png)

и при отправке я хочу, чтобы закрывалось общее модальное окно, как при нажатие на крестик
![image](https://user-images.githubusercontent.com/55946429/208852130-e1aad3ac-75f8-49dc-a598-7110453fe14b.png)

Описал максимально подробно. надеюсь вы меня поняли и поможете мне.

**Comment by AlekseySokolov** [comment]
Добрый день
<img width="830" alt="image" src="https://user-images.githubusercontent.com/28859492/208857541-c5643166-1f25-4311-94d8-49203a134725.png">

закрыть модалку можно через эти redux actions
close таргетный, требует id, destroy закроет все оверлеи, если у вас 1 модалка в этом кейсе, то destroy подойдет.
в sendSign в нужный момент сделать dispatch одного из них
