### ISSUE TITLE
Doubleclick

### ISSUE THREAD

**Issue by vladislavnikonov** [i-novus-llc/n2o-framework#159]
Добрый день, как добавить doubleclick на запись в таблице?
![image](https://user-images.githubusercontent.com/55946429/209087458-41281641-b84e-456d-a1ac-254ed472eb63.png)

Хочу чтобы при двойном клике на строку открывалось модальное окно

**Comment by iryabov** [comment]
Есть возможность только задать действие одинарного клика. Двойного клика в компонентах N2O нет нигде.
https://n2oapp.net/docs/guides/xml/widget#rows
