### ISSUE TITLE
Передача в провайдер данных список без айди (версия 7.20)

### ISSUE THREAD

**Issue by luuzhel** [i-novus-llc/n2o-framework#164]
<img width="727" alt="Снимок экрана 2023-01-12 в 17 47 27" src="https://user-images.githubusercontent.com/121654260/212047001-7f79a4ca-5d17-40c8-8910-fdcde4b325a7.png">

Добрый день, возможно ли отправить в провайдер данных РЕСТ отправить такой список без айди?

**Comment by iryabov** [comment]
Да, это должно работать. Провайдеру рест айди не нужен, с т.зр. N2O

**Comment by Rgalina** [comment]
Да

**Comment by luuzhel** [comment]
Вот только не работает, выходит ошибка NPE или no body. Может у вас есть такой пример?

**Comment by luuzhel** [comment]
Больше не актуально
