### ISSUE TITLE
Не получается отправить 2 аргумента: критерий и примитив в джава провайдер

### ISSUE THREAD

**Issue by luuzhel** [i-novus-llc/n2o-framework#165]
<img width="499" alt="Снимок экрана 2023-01-19 в 13 51 05" src="https://user-images.githubusercontent.com/121654260/213374875-05ec55ba-f892-4ca6-ba09-6ed5d564fc99.png">

Здравствуйте, в провайдер успешно уходит критерий (с одним полем), при добавлении дополнительного аргумента(примитив=строка), этот аргумент записывается в критерий, а само, отправляемое в критерий, поле не уходит.
Пробовал заводить дополнительное поле в критерии и отправлять туда, тоже не уходит.

Хочу добиться того, чтобы отправлялись значение соседнего фильтра (profile), и значение из input-select текущего documentName.
<img width="761" alt="Снимок экрана 2023-01-19 в 13 55 49" src="https://user-images.githubusercontent.com/121654260/213375638-fa2b063c-22fe-4124-b376-c0f4a8f54f91.png">

Можете подсказать, как этого добиться?

**Comment by Rgalina** [comment]
Сделать так, чтобы критерия принимала несколько полей. Это должно работать, вот пример https://sandbox.n2oapp.net/editor/WLNK6/?file=person.query.xml

**Comment by luuzhel** [comment]
Дело в том, что в запросе из UI по настройка должно отправляться из input-select documentName и профиль, по факту отправляется только один аргумент и мапится в профиль(либо инпут-селект, если заполнен, либо профиль, если заполнен)

**Comment by luuzhel** [comment]
Больше не актуально
